name: publish container images
on:
  push:
    branches: [master]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container_image: ["frontend", "backend"]

    steps:
      - name: source repository
        uses: actions/checkout@v2
    
      - name: Login in to quay.io registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build container image and push - ${{ matrix.container_image }}
        env:
          TARGET_BUILD: ${{ matrix.container_image }}
          BUILD_TAG: master
        run: |
          docker build -t quay.io/jkandasa/django-blog-${TARGET_BUILD}:${BUILD_TAG} -f docker/${TARGET_BUILD}.Dockerfile .
          docker push quay.io/jkandasa/django-blog-${TARGET_BUILD}:${BUILD_TAG}
